baseURL = "https://kejaripalu.github.io/"
languageCode = "id-id"
title = "Kejaksaan Negeri Palu"
# theme = "kejari-palu"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  description = "Portal Resmi Kejaksaan Negeri Palu"
  author = "Kejaksaan Negeri Palu"
  tagline = "Melayani Masyarakat dengan Sepenuh Hati"
  address = "Jl. Moh. Yamin No. 97 Palu"
  phone = "0451-421750"
  email = "kejari.plw@gmail.com"
  whatsapp = "081112020367"

[menu]
  [[menu.main]]
    name = "Beranda"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Profil"
    url = "/profil"
    weight = 2
  [[menu.main]]
    name = "Berita"
    url = "/berita"
    weight = 3
  [[menu.main]]
    name = "Layanan"
    url = "/layanan"
    weight = 4
  [[menu.main]]
    name = "Kontak"
    url = "/kontak"
    weight = 5

[taxonomies]
  kategori = "kategori"
  tag = "tags"

[pagination]
  pagerSize = 9
